export const services = [
  { id: "poiniko-dikaio", title: "Ποινικό Δίκαιο", desc: "Υπεράσπιση και νομική εκπροσώπηση σε ποινικές υποθέσεις.", color: "bg-teal" },
  { id: "astiko-dikaio", title: "Αστικό Δίκαιο", desc: "Επίλυση αστικών διαφορών και προάσπιση δικαιωμάτων.", color: "bg-sage" },
  { id: "oikogeneiako-dikaio", title: "Οικογενειακό Δίκαιο", desc: "Διαζύγια, διατροφές, επιμέλεια τέκνων και οικογενειακές διαφορές.", color: "bg-orange" },
  { id: "enoxiko-dikaio", title: "Ενοχικό Δίκαιο", desc: "Συμβάσεις, αποζημιώσεις και διαφορές από ενοχικές σχέσεις.", color: "bg-red" },
  { id: "empragmato-dikaio", title: "Εμπράγματο Δίκαιο", desc: "Προστασία ιδιοκτησίας, νομής και κατοχής.", color: "bg-red" },
  { id: "klironomiko-dikaio", title: "Κληρονομικό Δίκαιο", desc: "Διαθήκες, αποδοχές κληρονομιάς και κληρονομικές διαφορές.", color: "bg-teal" },
  { id: "elegxos-titlon", title: "Έλεγχος τίτλων", desc: "Υποθηκοφυλακεία & Κτηματολόγια.", color: "bg-sage" },
  { id: "misthotikes-diafores", title: "Μισθωτικές Διαφορές", desc: "Εξώσεις, μισθώματα και διαφορές ιδιοκτητών-ενοικιαστών.", color: "bg-orange" },
  { id: "exodikastikos-mixanismos", title: "Εξωδικαστικός Μηχανισμός", desc: "Ρύθμιση οφειλών και προστασία δανειοληπτών.", color: "bg-red" },
  { id: "diakanonismos-ofeilon", title: "Διακανονισμός Οφειλών", desc: "Διαπραγματεύσεις με τράπεζες και πιστωτές.", color: "bg-teal" },
  { id: "metafraseis-epikyroseis", title: "Μεταφράσεις & Επικυρώσεις", desc: "Επίσημες μεταφράσεις και επικυρώσεις εγγράφων.", color: "bg-teal" },
  { id: "dikaio-allodapon", title: "Δίκαιο Αλλοδαπών", desc: "Άδειες διαμονής, ιθαγένεια και νομιμοποίηση.", color: "bg-sage" },
  { id: "somateia-symvouleytiki", title: "Σωματεία & Συμβουλευτική", desc: "Ίδρυση σωματείων και νομική συμβουλευτική.", color: "bg-orange" },
];
